### ISSUE TITLE
Cierre en Android 9

### ISSUE THREAD

**Issue by esalessandrxx** [applifycu/simple#26]
Error:

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.arr.simple/com.arr.simple.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6810)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
 at com.arr.didi.Didi.loadBitmap(Didi.java:207)
 at com.arr.didi.Didi.getBitmap(Didi.java:77)
 at com.arr.simple.MainActivity.loadProfile(MainActivity.java:207)
 at com.arr.simple.MainActivity.lambda$onCreate$2(MainActivity.java:195)
 at com.arr.simple.MainActivity.$r8$lambda$-ap5qMnsASuYyIKqANWtPncKzS0(Unknown Source:0)
 at com.arr.simple.MainActivity$$ExternalSyntheticLambda2.onDestinationChanged(Unknown Source:2)
 at androidx.navigation.NavController.addOnDestinationChangedListener(NavController.kt:420)
 at com.arr.simple.MainActivity.onCreate(MainActivity.java:165)
 at android.app.Activity.performCreate(Activity.java:7224)
 at android.app.Activity.performCreate(Activity.java:7213)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
 ... 11 more
```

**Comment by esalessandrxx** [comment]
update report
